menu:
#- {name: 'people', url: '/people'}
- {name: 'Publications', url: '/publications'}
- {name: 'Teaching', url: '/teaching'}
- {name: 'CV', url: '/cv'}
- {name: 'Contact', url: '/contact'}

#people:
#- {name: 'Primary Investigator', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/primary-investigator.jpg', url: 'primary-investigator'}
#- {name: 'Lab Technician', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/lab-technician.jpg', url: 'lab-technician'}
#- {name: 'Graduate Student', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/graduate-student.jpg', url: 'graduate-student'}

teaching:
- {place: 'carlos', year: '2017-2018', name: 'Linear networks analysis and synthesis', degree: 'Bachelor in Telecommunication Technologies Engineering (1st year)', description: ''}
- {place: 'carlos', year: '2017-2018', name: 'Linear systems', degree: 'Bachelor in Mobile and Space Communications Engineering (2nd year)', description: ''}
- {place: 'carlos', year: '2017-2018', name: 'Linear systems', degree: 'Bachelor in Telecommunication Technologies Engineering (2nd year)', description: ''}
- {place: 'carlos', year: '2017-2018', name: 'Linear systems', degree: 'Bachelor in Telematics Engineering (2nd year)', description: ''}
- {place: 'carlos', year: '2018-2019', name: 'Linear systems', degree: 'Bachelor in Mobile and Space Communications Engineering (2nd year)', description: ''}
- {place: 'carlos', year: '2018-2019', name: 'Linear systems', degree: 'Bachelor in Telecommunication Technologies Engineering (2nd year)', description: ''}
- {place: 'carlos', year: '2018-2019', name: 'Linear systems', degree: 'Bachelor in Telematics Engineering (2nd year)', description: ''}


#- {name: 'Vector Calculus', url: 'vector-calculus'}
#- {name: 'Quantum Mechanics', url: 'quantum-mechanics'}
#- {name: 'Stellar Structures', url: 'stellar-structures'}

social:
- {icon: 'fab fa-github', link: 'https://github.com/sarapv'}
- {icon: 'fab fa-linkedin', link: 'https://www.linkedin.com/in/sara-p%C3%A9rez-vieites-732425122/'}
- {icon: 'ai ai-google-scholar', link: 'https://scholar.google.es/citations?user=MzPUI0AAAAAJ&hl=es'}
- {icon: 'fab fa-orcid', link: 'https://orcid.org/0000-0003-1572-4258'}

contacts:
- {name: 'Dr. Sara Pérez Vieites', title: 'Postdoctoral Researcher', department: 'CERI Systèmes Numériques (Digital Systems)', institution: 'IMT Nord Europe', institution_address: 'Cité Scientifique, Rue Guglielmo Marconi, 59650, Villeneuve-d’Ascq', phone: '', email: 'sara.perez-vieites@imt-nord-europe.fr', office: '', image: 'assets/img/cropped-IMT_Nord_Europe_.png'}
