menu:
- {name: 'News', url: '/news'}
- {name: 'Publications', url: '/publications'}
- {name: 'Teaching', url: '/teaching'}
- {name: 'CV', url: '/cv'}
- {name: 'Contact', url: '/contact'}

social:
- {icon: 'fab fa-github fa-3x', link: 'https://github.com/jayrcausal'}
- {icon: 'ai ai-google-scholar fa-3x', link: 'https://scholar.google.es/citations?user=0000000'}
